### ISSUE TITLE
Suffixes are not handled well

### ISSUE THREAD

**Issue by nsmarkop** [nsmarkop/plover_last_translation#1]
Suffixes and similar concepts count as separate translations in the Plover translator. For example, `AR/KAEUPB` for `arcane` works fine and will repeat `arcane` with the use of this macro, but if you do `AR/KAEUPB/S` to get `arcanes` then the final `S` counts as its own translation and will be the repeated part.

See:
![image](https://user-images.githubusercontent.com/4577561/35951905-173905b2-0c43-11e8-8289-d87fc40667e2.png)

The top line is the list of recent translations and the last line is the most recent one of those. The boolean was just a check for the "is_retrospective_command" property of a plover.translation.Translation to see if I could maybe step backwards through them to get to a "normal" translation but they are not considered as such.

**Comment by tkpwaeub** [comment]
Could you use last_words from formatting.py? Then have "get last word" be a separate command, and maybe change the name of this plugin.

**Comment by nsmarkop** [comment]
Thanks!

With bebcb2f I exposed the various options in the RetroFormatter from formatting.py as new plugins: repeat_last_word, repeat_last_fragment and repeat_last_character with each having some options to repeat a specified number of times now.

Things seem to be working for them from my limited testing so I'll close this issue with those as the options for resolving this. PyPI update coming soon.
